import { betterAuth } from 'better-auth';
import { prismaAdapter } from 'better-auth/adapters/prisma';
import { prisma } from '@billing/database';
import { loadServerEnv } from '@billing/config';

/**
 * Better Auth (TICKET-003 / TICKET-004).
 *
 * Chosen over a hand-rolled implementation: it owns password hashing (scrypt),
 * session issuance and rotation, email verification, and cookie handling —
 * the parts the Security Doc §2 warns against building from scratch — while
 * running entirely against our own Postgres with no third-party service.
 *
 * Authorization is deliberately NOT delegated here. Better Auth answers
 * "who are you?"; organisation membership and RBAC are enforced by this
 * application (Security Doc §2).
 */

const env = loadServerEnv();
const isProd = env.NODE_ENV === 'production';

export const auth = betterAuth({
  secret: env.BETTER_AUTH_SECRET,
  baseURL: env.BETTER_AUTH_URL,
  basePath: '/api/v1/auth',

  database: prismaAdapter(prisma, { provider: 'postgresql' }),

  emailAndPassword: {
    enabled: true,
    // Security Doc §4 asks for 10–12 minimum; we take the stricter bound.
    minPasswordLength: 12,
    maxPasswordLength: 256,
    // TODO(post-Phase-2): set to true once the transactional email provider is
    // wired up. Deliberately false until then — with no way to deliver a
    // verification email, enforcing it would lock every new user out.
    // Organisation creation is NOT gated on verification by decision.
    requireEmailVerification: false,
    autoSignIn: true,
  },

  session: {
    expiresIn: env.SESSION_EXPIRES_IN_SECONDS,
    updateAge: env.SESSION_UPDATE_AGE_SECONDS,
    // Session rows are read on every request to support instant revocation
    // (Security Doc §4: logout-all-devices, removal while logged in).
    cookieCache: { enabled: false },
    additionalFields: {
      /**
       * The active tenant, stored on the session row.
       *
       * `input: false` is the security-critical part: it makes the field
       * server-writable only, so a client cannot set or change its own tenant
       * context by posting to a Better Auth endpoint. It is written solely by
       * /auth/switch-organisation and organisation creation, both of which
       * verify membership first.
       */
      activeOrganisationId: { type: 'string', required: false, input: false },
    },
  },

  advanced: {
    useSecureCookies: isProd,
    defaultCookieAttributes: {
      httpOnly: true, // Never readable by JS — no localStorage tokens.
      sameSite: 'lax', // CSRF mitigation for cookie auth (Tech Arch Doc §13).
      secure: isProd,
      path: '/',
    },
    // Our schema uses uuid PKs generated by Postgres defaults.
    database: { generateId: false },
  },

  user: {
    modelName: 'user',
    fields: { emailVerified: 'emailVerified', createdAt: 'createdAt', updatedAt: 'updatedAt' },
    additionalFields: {
      firstName: { type: 'string', required: true, input: true },
      lastName: { type: 'string', required: false, input: true },
      isActive: { type: 'boolean', required: false, input: false, defaultValue: true },
    },
  },

  trustedOrigins: env.CORS_ORIGINS.split(',').map((o) => o.trim()).filter(Boolean),
});

export type Auth = typeof auth;
